---
seed: 1984

num_workers: 4
experiment_name: "2020-11-15"

num_classes: 2

train_parameters:
  batch_size: 1
  rotate90: True

checkpoint_callback:
  type: pytorch_lightning.callbacks.ModelCheckpoint
  # filepath: "2020-11-15"
  monitor: val_loss
  verbose: True
  mode: max
  save_top_k: -1

val_parameters:
  batch_size: 10
  iou_threshold: 0.4
  rotate90: True
  box_min_size: 5

prior_box:
  type: wasp.retinaface.priors.priorbox
  min_sizes: [[16, 32], [64, 128], [256, 512]]
  steps: [8, 16, 32]
  clip: False

image_size: [256, 256]

loss_weights:
  localization: 2
  classification: 1
  landmarks: 1

test_parameters:
  variance: [0.1, 0.2]
